name: "OpenSSF Scoring"
on: 
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:   

permissions:
  contents: write
  pull-requests: write 
  issues: write
  packages: none

jobs:
  security-scoring:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: OpenSSF Scorecard Monitor
        uses: UlisesGascon/openssf-scorecard-monitor@0af2f73467fbe5eb6296e91ba38d60ecc4b7be13 # v2.0.0-beta6
        with:
          scope: __automation__/scorecard/scope.json
          database: __automation__/scorecard/database.json
          report: docs/06-reporting/01-scorecard.md
          auto-commit: true
          auto-push: true
          generate-issue: true
          report-tags-enabled: true
          issue-title: "OpenSSF Scorecard Report Updated!"
          issue-assignees: "inigomarquinez,ulisesGascon"
          issue-labels: "maintainers-agenda"
          github-token: ${{ secrets.GITHUB_TOKEN }}
          max-request-in-parallel: 10
          discovery-enabled: true
          discovery-orgs: 'onebeyond,guidesmiths'
      - name: Create Pull Request
        uses: gr2m/create-or-update-pull-request-action@77596e3166f328b24613f7082ab30bf2d93079d5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
            commit-message: 'docs: OpenSSF Scorecard Report Updated'
            title: OpenSSF Scorecard Report Updated
            body: 'OpenSSF Scorecard Report Updated. cc: @ulisesGascon @inigomarquinez'
            assignees: ${{ github.actor }}
            labels: maintainers-agenda
            branch: openssf-scorecard-report-updated
            update-pull-request-title-and-body: true